# Generated by Django 2.2.3 on 2019-10-25 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_foodtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodtype',
            old_name='typenames',
            new_name='typename',
        ),
    ]
