# Generated by Django 2.2.3 on 2019-10-25 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_good'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Good',
            new_name='Goods',
        ),
    ]
